version: "2.2"

services:
  ahml-fondos:
    build: .
    container_name: ahml-fondos
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - ahml-fondos-network

networks:
  ahml-fondos-network:
    driver: bridge
