"""create record_file_typology table

Revision ID: 0441a4404f2f
Revises: b55ccadb12af
Create Date: 2025-11-05 10:38:22.723401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0441a4404f2f'
down_revision = 'b55ccadb12af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_file_typology',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_file_id', sa.Integer(), nullable=False),
    sa.Column('typology_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['record_file_id'], ['record_file.id'], ),
    sa.ForeignKeyConstraint(['typology_id'], ['typology.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_file_id', 'typology_id', name='uq_recordfile_typology')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_file_typology')
    # ### end Alembic commands ###
