"""fs

Revision ID: 112b524972bb
Revises: 3f368b8b39b7
Create Date: 2026-01-14 13:33:06.123836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112b524972bb'
down_revision = '3f368b8b39b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('box_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'physical_location', ['physical_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('box_ibfk_1'), 'location', ['physical_location_id'], ['id'])

    # ### end Alembic commands ###
