"""size

Revision ID: 2a2153aa4d6e
Revises: c8d339b21d76
Create Date: 2025-11-18 12:12:29.320220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a2153aa4d6e'
down_revision = 'c8d339b21d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=1000),
               type_=sa.String(length=1500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.String(length=1500),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
