"""create record_file table

Revision ID: 5ab99bcabd29
Revises: df975e24d1f2
Create Date: 2025-11-05 11:03:39.763898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ab99bcabd29'
down_revision = 'df975e24d1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.drop_column('typologies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typologies', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###
