"""is_active

Revision ID: 6cc3aa6bee29
Revises: 2a2153aa4d6e
Create Date: 2025-11-20 13:13:06.778713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc3aa6bee29'
down_revision = '2a2153aa4d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deterioration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('typology', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typology', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('deterioration', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
