"""create schema typology y record

Revision ID: 6db762d9834e
Revises: d7cb220ce129
Create Date: 2025-11-05 14:26:39.724988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db762d9834e'
down_revision = 'd7cb220ce129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_file_typology',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_file_id', sa.Integer(), nullable=False),
    sa.Column('typology_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['record_file_id'], ['record_file.id'], ),
    sa.ForeignKeyConstraint(['typology_id'], ['typology.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_file_id', 'typology_id', name='uq_recordfile_typology')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_file_typology')
    # ### end Alembic commands ###
