"""create schema movement

Revision ID: b1bc4076937c
Revises: 6db762d9834e
Create Date: 2025-11-05 14:26:58.516432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bc4076937c'
down_revision = '6db762d9834e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_file_id', sa.Integer(), nullable=False),
    sa.Column('moved_by_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('origin_status', sa.String(length=50), nullable=True),
    sa.Column('destination_status', sa.String(length=50), nullable=True),
    sa.Column('moved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moved_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['record_file_id'], ['record_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement_history')
    # ### end Alembic commands ###
