"""create record_file table

Revision ID: b55ccadb12af
Revises: 3fbef5d719ec
Create Date: 2025-11-05 10:37:51.688017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55ccadb12af'
down_revision = '3fbef5d719ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_code', sa.String(length=255), nullable=False),
    sa.Column('file_number', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('typologies', sa.JSON(), nullable=True),
    sa.Column('sensitive_data', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('box_number', sa.String(length=50), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('file_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('last_preservation_date', sa.Date(), nullable=True),
    sa.Column('last_fund_date', sa.Date(), nullable=True),
    sa.Column('deterioration_status_id', sa.Integer(), nullable=True),
    sa.Column('deterioration_status_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deterioration_status_id'], ['deterioration.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_file')
    # ### end Alembic commands ###
