"""create record_file_typology table

Revision ID: c0d204086fe4
Revises: 0441a4404f2f
Create Date: 2025-11-05 10:39:16.340017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d204086fe4'
down_revision = '0441a4404f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_file_id', sa.Integer(), nullable=False),
    sa.Column('moved_by_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('origin_status', sa.String(length=50), nullable=True),
    sa.Column('destination_status', sa.String(length=50), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moved_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['record_file_id'], ['record_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement_history')
    # ### end Alembic commands ###
