"""ad

Revision ID: c583cf48a518
Revises: 6cc3aa6bee29
Create Date: 2025-11-27 11:01:35.340237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c583cf48a518'
down_revision = '6cc3aa6bee29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_reference_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.drop_column('previous_reference_code')

    # ### end Alembic commands ###
