"""f

Revision ID: c71afd8c9120
Revises: 35769602aee6
Create Date: 2026-01-22 13:05:23.526799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71afd8c9120'
down_revision = '35769602aee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_diagnosis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revision_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['record_file_id'], ['record_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_diagnosis_catalog',
    sa.Column('record_diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_catalog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_catalog_id'], ['diagnosis_catalog.id'], ),
    sa.ForeignKeyConstraint(['record_diagnosis_id'], ['record_diagnosis.id'], ),
    sa.PrimaryKeyConstraint('record_diagnosis_id', 'diagnosis_catalog_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_diagnosis_catalog')
    op.drop_table('record_diagnosis')
    op.drop_table('diagnosis_catalog')
    # ### end Alembic commands ###
