"""size

Revision ID: c8d339b21d76
Revises: f9681b5a9b1a
Create Date: 2025-11-18 12:10:17.572331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8d339b21d76'
down_revision = 'f9681b5a9b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
