"""ad

Revision ID: ce676ce3d4ef
Revises: cfb7e4844adf
Create Date: 2025-11-27 13:56:30.553579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce676ce3d4ef'
down_revision = 'cfb7e4844adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.alter_column('box_number',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               type_=sa.String(length=52),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.alter_column('box_number',
               existing_type=sa.String(length=52),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
