"""ad

Revision ID: cfb7e4844adf
Revises: c583cf48a518
Create Date: 2025-11-27 11:12:53.527680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb7e4844adf'
down_revision = 'c583cf48a518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_sizes', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.drop_column('document_sizes')

    # ### end Alembic commands ###
