"""diagnosis.

Revision ID: d6a25fcfbccb
Revises: 112b524972bb
Create Date: 2026-01-16 14:55:16.546047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a25fcfbccb'
down_revision = '112b524972bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_diagnosis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_file_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_catalog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revision_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_catalog_id'], ['diagnosis_catalog.id'], ),
    sa.ForeignKeyConstraint(['record_file_id'], ['record_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_diagnosis')
    op.drop_table('diagnosis_catalog')
    # ### end Alembic commands ###
