"""diagnosis.

Revision ID: d7f52565f22b
Revises: d6a25fcfbccb
Create Date: 2026-01-16 15:10:15.915370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7f52565f22b'
down_revision = 'd6a25fcfbccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_diagnosis_catalog',
    sa.Column('record_diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_catalog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_catalog_id'], ['diagnosis_catalog.id'], ),
    sa.ForeignKeyConstraint(['record_diagnosis_id'], ['record_diagnosis.id'], ),
    sa.PrimaryKeyConstraint('record_diagnosis_id', 'diagnosis_catalog_id')
    )
    with op.batch_alter_table('diagnosis_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('record_diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('record_diagnosis_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('severity')
        batch_op.drop_column('diagnosis_catalog_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_diagnosis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosis_catalog_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('severity', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('record_diagnosis_ibfk_1'), 'diagnosis_catalog', ['diagnosis_catalog_id'], ['id'])
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('diagnosis_catalog', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    op.drop_table('record_diagnosis_catalog')
    # ### end Alembic commands ###
