"""create loan table

Revision ID: df975e24d1f2
Revises: c0d204086fe4
Create Date: 2025-11-05 10:40:12.270010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df975e24d1f2'
down_revision = 'c0d204086fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_file_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=False),
    sa.Column('loaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loaded_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['record_file_id'], ['record_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    # ### end Alembic commands ###
