"""add box_id foreign key to record_file

Revision ID: f0e38364a75b
Revises: ce676ce3d4ef
Create Date: 2026-01-13 13:56:42.800207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0e38364a75b'
down_revision = 'ce676ce3d4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('box',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('box_number', sa.String(length=50), nullable=False),
    sa.Column('physical_location_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['physical_location_id'], ['physical_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_box_box_number'), ['box_number'], unique=True)

    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'box', ['box_id'], ['id'])
        batch_op.drop_column('box_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_number', mysql.VARCHAR(collation='utf8_unicode_ci', length=52), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('box_id')

    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_box_box_number'))

    op.drop_table('box')
    op.drop_table('physical_location')
    # ### end Alembic commands ###
