from app.models.user import User
from app.models.catalog_key import CatalogKey
from app.models.fund import Fund
from app.models.section import Section
from app.models.series import Series
from app.models.location import Location
from app.models.deterioration import Deterioration
from app.models.typology import Typology
from app.models.record_file import RecordFile
from app.models.record_file_typology import RecordFileTypology
from app.models.movement import MovementHistory
from app.models.loan import Loan
from app.models.physical_location import PhysicalLocation
from app.models.box import Box
from app.models.diagnosis_catalog import DiagnosisCatalog
from app.models.record_diagnosis import RecordDiagnosis
from app.models.record_diagnosis_catalog import record_diagnosis_catalog
